### ISSUE TITLE
Feature Request: M204 S Parameter

### ISSUE THREAD

**Issue by notnyt** [dc42/RepRapFirmware#101]
Marlin and other firmware take the S parameter to set normal move speeds.  Many slicers (cura) use this to control acceleration for different portions of the print.  Is it possible to support this?  If you need I'll fork, patch, and submit a pull request.

**Comment by dc42** [comment]
RRF implements M204 as described on the reprap,org wiki as follows:

"Marlin notes: After Mar11-2015, the M204 options have changed in Marlin:
P = Printing moves
R = Retract only (no X, Y, Z) moves
T = Travel (non printing) moves
The command M204 P800 T3000 R9000 sets the acceleration for printing movements to 800mm/s^2, for travels to 3000mm/s^2 and for retracts to 9000mm/s^2."

I left out the R parameter because it seems to be pointless, as extruder acceleration is set using M201.

**Comment by notnyt** [comment]
Ah, I see in Marlin:

  if (code_seen('S')) {  // Kept for legacy compatibility. Should NOT BE USED for new developments.
    planner.travel_acceleration = planner.acceleration = code_value_linear_units();           SERIAL_ECHOLNPAIR("Setting Print and Travel Acceleration: ", planner.acceleration);
  }

**Comment by dc42** [comment]
Implemented in version 1.19 beta 2.
