### ISSUE TITLE
WS2811/WS2812 LED strip control

### ISSUE THREAD

**Issue by Armadillo1** [dc42/RepRapFirmware#185]
Would be a useful feature to be able to tell from a distance whether the hotend is cold (e.g. green), heating (yellow) or hot (red). 
An option for ambient (low light), working lights when repairing the printer (=bright), etc would be nice and helpful.

Something to consider.
Thanks

**Comment by lordgort** [comment]
yes yes yes XD this would be awesome

**Comment by lordgort** [comment]
but i think this is more a request, not an issue

**Comment by dc42** [comment]
We will definitely not be supporting the WS2811/WS2812. The reason is that they use a nonstandard protocol that means the processor cannot do anything else (even process interrupts) while writing to these LEDs. That is unacceptable; it would lead to lost steps, lost serial input, possibly also network disconnections.

However, we have implemented a driver for DotStar LED strips in the latest RRF source code. These LED strips use standard SPI MOSI ands SCLK signals, so not only does the processor not need to give them its undivided attention, it can use DMA to send the data. To use them on the Duet WiFi or Duet Ethernet, you would need to make a hardware adapter to level shift the MOSI and SCLK signals to 5V, also to gate SCLK with your chosen /CS pin. You could do all of this using a single 74HCT02 chip. You would also need to enable the DotStar support for the Duet 2 build of RRF.

**Comment by svs072477** [comment]
Studying the topic with WS2812 came across two projects using DMA, perhaps it will be useful.
https://www.pjrc.com/non-blocking-ws2812-led-library/
https://drive.google.com/file/d/0B5dbvc_yPqJHQ2FEUXpkR3NocnM/view?usp=sharing

**Comment by dc42** [comment]
It may well be possible, but it is inefficient, and the timing accuracy would depend on what other DMA is taking place at the same time. Both the network interface SPI and the SD card use a lot of bandwidth, e.g. 20MBytes/sec for the SD card. DotStar is a better solution.

**Comment by svs072477** [comment]
DotStar of course better. And have you had experience with other SPI LED strips? For example APS 102 https://cdn-shop.adafruit.com/datasheets/APA102.pdf In Russia, they are easier to buy than Dotstar

**Comment by svs072477** [comment]
I realized that asked a stupid :)

**Comment by dc42** [comment]
You mean because the DotStar originally used the APA102? That's my reading of the tech details section of https://www.adafruit.com/product/2238?length=1.

**Comment by svs072477** [comment]
Yes, Yes, I already wrote above that asked a stupid question :)

**Comment by stavros-k** [comment]
If you have a lot of ws2812 hanging around and you don't want get apa102 or other supported led strips. You can get an arduino (as a cheap as 2$) and connect it with duet wifi to get the status and control the leds.
Duet <-> arduino - > leds
