### ISSUE TITLE
support for RADDS/RAMPS-FD with wifi/eth

### ISSUE THREAD

**Issue by Cosik** [dc42/RepRapFirmware#193]
Hi,

Currently I'm trying to run reprap firmware on my Arduino Due with eth shield with W5100. Based firmware is working but now I'm trying to run eth part. So my question is where I can find definition of SPI for eth/wifi module? Do you know if W5100 will work with W5500 or better connect ESP to due?

Do you think when it will be ready it is good idea to add this to your repo and support them officialy?

**Comment by dc42** [comment]
When we implemented the Duet Ethernet, we determined that the W5100 was unsuitable due to having insufficient buffer memory for IP packets. The Duet Ethernet uses the W5500.

The Arduino Due is an obsolete board using an obsolescent processor. It was badly designed in the first place because the processor supports Ethernet and high speed SD card access, but the design of the Due made it impossible to use either of them. If you want to use a processor board with an Arduino-compatible form factor, consider using the SAME70-XPLD instead.
