### ISSUE TITLE
(feature request) Read-only web inteface

### ISSUE THREAD

**Issue by crispy1066** [dc42/RepRapFirmware#21]
It'd be nice to have a non-logged in user able to see the printer's current status, but lock out all controls.  In several use cases, many people are going to want to be able to check if the printer is free or how long the current print will take from their desk, but you wouldn't necessarily want everyone to have the ability to control the printer through the web interface.

**Comment by chrishamm** [comment]
I won't implement this because it's too much work for a feature I won't be using, but I suggest an alternative: You can change the machine password on the fly by sending M551 and this way prevent unauthorized users from accessing it.

You could add such a code to the beginning and end of your own G-code files and this way implement a simple authorization mechanism. This way it would be possible to lock out other users who want to access the machine when a print job is running. If you want to disable password authentification again, just send M551 Preprap (reprap is the default password).
