### ISSUE TITLE
Duet Wifi: 3.01-RC4 not installable (Duet2CombinedIAP.bin not found)

### ISSUE THREAD

**Issue by bernhardberger** [dc42/RepRapFirmware#371]
I just tried to upgrade to the newest Duet2Combined.bin for 3.01-RC4 on my Duet Wifi. (Upgrading from 3.01-RC3). However it says: 

> M997 S0 - Error: In-Application programming binary Duet2Combined**IAP**.bin not found.

![image](https://user-images.githubusercontent.com/2110083/76860022-a43c9300-685a-11ea-8e0c-1d09d8cd46c4.png)

I have the `iap4e.bin` from this repository inside my `/sys/` folder however: https://github.com/dc42/DuetIAP/tree/master/Release (updates from RRF2 to RRF3 to RRF3.01-RC3 worked without a problem)

**Comment by Billtopia** [comment]
Did you upgrade to v3.0 first? https://github.com/dc42/RepRapFirmware/releases/tag/3.0
AFAIK there is no direct upgrade to latest from v2.x. You need to download the full zip from above, install it, then upgrade to the latest as in the whats_new.md as some files were updated in v3.0 that are required to be updated in order to allow the firmware to be updated past v3.0.

**Comment by bernhardberger** [comment]
Sorry, I forgot to mention that: I'm trying to update from 3.01-RC3

**Comment by bernhardberger** [comment]
Nevermind. Just found the missing Duet2Combined IAP binary in the zip archive from the 3.0 release linked above.

Can be closed.

However: I wished the necessary assets would be linked in the releases. Upgrading FW is often kind of an adventure searching through a ton of previous releases for the required files, and in some cases even different repositories :/
