### ISSUE TITLE
Handle CAN bus disconnects better

### ISSUE THREAD

**Issue by T3P3** [dc42/RepRapFirmware#769]
CAN connected expansion boards, when disconnected from the bus, should (optionally?) follow a controlled and safe shutdown procedure. The mainboard should raise an event with the default action being similar to a heater fault, assuming there is a heater on the expansion board.

https://forum.duet3d.com/topic/31502/no-trp-trigger-after-prolonged-connection-issue-to-can-board

https://forum.duet3d.com/post/312467

**Comment by gloomyandy** [comment]
Hi Tony/David. Here are some random thoughts I posted in another place on this subject a few days ago. I thought it might be worth capturing them here:

I'm not sure what the best way is to handle loss of can-fd communication. The problem is that whatever you do it all has to be done on the toolboard (because it is no longer in touch with the main board). At the moment it simply maintains the current state of things. You can't easily get it to run scripts or anything as they normally come from the sd card and are executed by the main board, the toolboards have no gcode parsing logic. 

Personally I'd prefer that unless told otherwise if the board does not see a sync message for some period of time (possibly settable), it should perform a reset. I'd also add code so that the main board can detect a toolboard coming back from a reset and trigger an event. That would allow the main board to resend configuration information or possibly deal with issues by turning on fans etc.

Actually I think most of what is needed is already there. When a toolboard starts it sends out an announce message and basically keeps doing that until it gets a response from a main board. That message could be used by the main board to raise an event. Once past that step it gets command and sync messages from the main board. So in theory the toolboard can detect a problem by looking for missing sync messages and could then reset. If the toolboard has any sort of temperature sensor or heater it will be reporting details of that on a regular basis so in theory the main board could detect the loss of control if it does not see a report for some time. Of course there is not much that it can do in that situation other than perhaps raise an alarm or shutdown all of the systems power (which may or may not be a good idea). It should certainly be possible to raise some sort of event in that case. Not sure if there is any sort of regular message back from a board that does not have any sensors, but from a safety point of view I'm not sure if that matters, if it only has a motor attached then not having any reports back is not really any different from a direct stepper motor which does not give you any motion reports.

**Comment by T3P3** [comment]
related requirement: https://github.com/Duet3D/RepRapFirmware/issues/541

**Comment by dc42** [comment]
In 3.5.0-beta.4 an event is generated if the main board stops receiving status messages from a CAN-connected expansion board, and if an CAN-connected expansion board announces itself again (which will happen if it resets).

**Comment by gloomyandy** [comment]
Are you planning on doing anything on the expansion board side if communication seems to be lost with the main board?

**Comment by dc42** [comment]
Probably (i.e. turn heaters off), but not just yet.
