### ISSUE TITLE
Support ADXL345 sensors

### ISSUE THREAD

**Issue by T3P3** [dc42/RepRapFirmware#785]
There are artefacts when reading data.

**Comment by gloomyandy** [comment]
Link to branch containing ADXL345 support https://github.com/gloomyandy/RepRapFirmware/tree/3.5-dev-adxl

**Comment by dc42** [comment]
Do we want to support this, given the artefacts that the ADSL345 produces? Or support it in the code, but say we won't offer forum support for the ADXL345?

**Comment by T3P3** [comment]
@gloomyandy do you have more insight on the causes of the artifacts?

**Comment by gloomyandy** [comment]
Not really, I shared my results with David at the time. It looked to me as if activity on the SPI interface caused some sort of noise in the data. This took the form of a slight drop in one reading followed by a rise in the next. I'm not sure what the cause was but it seemed to be correlated with the SPI readings, so reading 20 values at time would cause a more significant (but less frequent) change in the data than say reading 10 at a time. Maybe the SPI activity induced some sort of voltage drop, or noise on the supply. It could just have been my test setup, so perhaps further testing is needed.

**Comment by dc42** [comment]
We are not planning to implement this. We now support LIS2DW accelerometers as well as LIS3DH and LIS3DSH.
