### ISSUE TITLE
Gcode comments ->  Object Model

### ISSUE THREAD

**Issue by T3P3** [dc42/RepRapFirmware#788]
Implement an mechanism for passing information from specifically formatted gcode comments into the Object Model

Add ;RRFJobInfo key = value parsing to M36 response

example:

;RRFJobInfo currentMaterial="Nylon"
;RRFJobInfo currentNozzleSize = "2mm"

this would allow slicer to pass further information through to a UI or macros that is available in the OM

**Comment by dc42** [comment]
Proposed specification:
- The line must be in this format:
;RRFJobInfo <variable_name>=<expression>
- The ";RRFJobInfo " must be exactly like that, including one space character separating RRFJobInfo from the variable name
- The variable name must follow the same rules as a local or global variable name in RRF
- Spaces are permitted around the = sign
- The expression may be any RRF expression. The type of the variable created will be the same as the type of the expression.
Still to be decided:
- What variable should be created? We could create a local variable so that it would automatically be deleted when the job finishes, but then it won't be accessible to other input channels. We could create a new namespace called jobinfo which would behave like global but be deleted when the job finishes (then we would in effect have a new keyword in the language). Or we could create a global variable called jobinfo_<variable_name> and then delete any global variables that start with jobinfo_ when the job finishes.

**Comment by T3P3** [comment]
A local variable will not work in at least one application as it needs to be available from the PanelDue.

Another option would be to have <variable_name> created if it does not exist and overwritten if it does.

**Comment by Tinchus2009** [comment]
This would be super helpful on creating check scripts at the start of a print for example. Great idea!

**Comment by dc42** [comment]
Implemented in 3.6-dev. The comments use the keyword "customInfo" not "RRFJobInfo" and the object model key is: job.fileInfo.customInfo.
