### ISSUE TITLE
Stop segmenting moves after Z bed compensation taper completes

### ISSUE THREAD

**Issue by T3P3** [dc42/RepRapFirmware#888]
to improve input shaping performance.

**Comment by chrishamm** [comment]
Changed in 0dec97fb78fec77e8161fd8e92e36a88b50da336

**Comment by AndyEveritt** [comment]
Some initial testing suggests that there is no improvement to input shaping because of this change. Will try some more test objects.

The expected issue is that IS is not being applied on the deceleration of a move that too long (relative to the bed mesh spacing)

Tested by printing 2 cubes on the bed with a large spacing between them (multiple times the bed mesh spacing), and enabling a taper for the mesh compensation.

Ringing was noticed on the edge immediately after the travel move (expected because IS won't be applied), but no change was seen before or after the taper height.

**Comment by chrishamm** [comment]
I just did a brief test on my setup with the latest firmware. I can confirm segmentation does NOT take place if the nozzle is above the defined fade height. To test this, I generated a mesh, enabled move debugging via `M111 P4 S1`, and drove the nozzle across the bed twice at varying heights. In the serial log I could see only two DMs if above the configured taper height (for X and Y respectively) and below the fade height I got several more DMs, which indicates that segmentation is taking place.
